services:
  personal-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
